"""DepTree Diffusion VAE — composes existing encoder/latent/skeleton with diffusion decoder.

Reuses the DepTreeVAE's encoder, latent space, skeleton decoder, and
phrase projector. Replaces only the autoregressive PhraseDecoder with
a TreeDiffusionDecoder that generates all content tokens simultaneously.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor

from lfm.generator.dep_tree_diffusion.config import DepTreeDiffusionConfig
from lfm.generator.dep_tree_diffusion.decoder import RoleLengthPredictor, TreeDiffusionDecoder
from lfm.generator.dep_tree_vae.config import DEP_REL_TO_ID, NUM_DEP_RELATIONS
from lfm.generator.dep_tree_vae.disentangle import DisentanglementModule
from lfm.generator.dep_tree_vae.encoder import SentenceEncoder
from lfm.generator.dep_tree_vae.latent import LatentSpace
from lfm.generator.dep_tree_vae.projector import PhraseZProjector

logger = logging.getLogger(__name__)


@dataclass
class DiffusionVAEOutput:
    """Container for forward pass outputs."""

    recon_loss: Tensor
    skeleton_loss: Tensor
    length_loss: Tensor
    kl_loss: Tensor
    dip_loss: Tensor
    topo_rho: Tensor
    topo_loss: Tensor
    disentangle: dict[str, Tensor]
    z_struct: Tensor
    z_content: Tensor
    mu: Tensor
    logvar: Tensor

    interp_loss: Tensor = torch.tensor(0.0)
    entropy_loss: Tensor = torch.tensor(0.0)

    @property
    def total_loss(self) -> Tensor:
        return (
            self.recon_loss
            + self.skeleton_loss
            + self.length_loss
            + self.kl_loss
            + self.dip_loss
            + self.topo_loss
            + self.interp_loss
            + self.entropy_loss
            + self.disentangle["total"]
        )


class DepTreeDiffusionVAE(nn.Module):
    """VAE with dependency-tree-structured diffusion decoder.

    Shared components (from DepTreeVAE):
      - SentenceEncoder → (mu, logvar)
      - LatentSpace → z_struct, z_content
      - SkeletonDecoder → role sequence from z_struct
      - PhraseZProjector → per-role memory from z_content
      - DisentanglementModule → HSIC + aux losses

    New: TreeDiffusionDecoder replaces autoregressive PhraseDecoder.
    """

    def __init__(self, cfg: DepTreeDiffusionConfig, vocab_size: int) -> None:
        super().__init__()
        self.cfg = cfg
        self.vocab_size = vocab_size

        full_vocab = vocab_size + 3
        decoder_vocab = cfg.spm_vocab_size + 2

        # Shared components (same as DepTreeVAE)
        self.encoder = SentenceEncoder(full_vocab, cfg)
        self.latent = LatentSpace(cfg.latent)
        # No separate skeleton decoder — role tokens are generated by the
        # diffusion decoder as part of the interleaved sequence (depth=0).
        self.phrase_projector = PhraseZProjector(
            content_dim=cfg.latent.content_dim,
            decoder_hidden_dim=cfg.diffusion.d_model,
            max_roles=cfg.skeleton.max_roles,
        )
        self.disentanglement = DisentanglementModule(
            cfg.disentanglement,
            struct_dim=cfg.latent.struct_dim,
            content_dim=cfg.latent.content_dim,
            content_vocab_size=full_vocab,
        )

        # Tree diffusion decoder — handles full interleaved vocab
        # (SPM tokens + BOS/EOS + role tokens)
        dcfg = cfg.diffusion
        full_decode_vocab = vocab_size + 3  # match encoder vocab
        self.diffusion_decoder = TreeDiffusionDecoder(
            vocab_size=full_decode_vocab,
            d_model=dcfg.d_model,
            num_layers=dcfg.num_layers,
            num_heads=dcfg.num_heads,
            dropout=dcfg.dropout,
            max_word_position=dcfg.max_word_position,
        )

        # Z → memory projection (full z → fixed number of cross-attention tokens)
        self._num_mem_tokens = dcfg.num_memory_tokens
        self._z_to_mem_proj = nn.Linear(cfg.latent.total_dim, dcfg.d_model * self._num_mem_tokens)

        # Per-role length predictor
        self.length_predictor = RoleLengthPredictor(
            z_dim=cfg.latent.total_dim,
            max_len=dcfg.max_tokens_per_role,
        )

        # Hierarchical: AR word expander for per-role token generation
        if dcfg.hierarchical:
            from lfm.generator.dep_tree_diffusion.word_expander import WordExpander
            self.word_expander = WordExpander(
                vocab_size=full_decode_vocab,
                d_model=dcfg.d_model,
                d_hidden=dcfg.word_expander_hidden,
                max_tokens=dcfg.max_tokens_per_role,
            )

        # IDs
        self._pad_id = 0
        self._bos_id = cfg.spm_vocab_size
        self._eos_id = cfg.spm_vocab_size + 1
        self._decoder_vocab = decoder_vocab
        self._role_offset = cfg.spm_vocab_size + 2

        # Z stats tracking (for downstream game calibration)
        self.register_buffer("_z_struct_mean", torch.zeros(cfg.latent.struct_dim))
        self.register_buffer("_z_struct_std", torch.ones(cfg.latent.struct_dim))
        self.register_buffer("_z_content_mean", torch.zeros(cfg.latent.content_dim))
        self.register_buffer("_z_content_std", torch.ones(cfg.latent.content_dim))

        # Word dropout rate (set by trainer)
        self._word_dropout_p: float = 0.0

    def forward(
        self,
        tokens: Tensor,
        lengths: Tensor,
        depths: Tensor,
        role_ids: Tensor,
        role_lengths: Tensor,
        kl_weight: float = 0.0,
        **kwargs,
    ) -> DiffusionVAEOutput:
        """Full forward pass with unified diffusion decoder.

        The diffusion decoder handles the entire interleaved sequence
        (role tokens + content tokens) in one denoising process. Tree
        depth from the dep parse controls the noise schedule: root
        tokens denoised first, leaves last.

        Args:
            tokens: (B, S) interleaved role+IPA token ids.
            lengths: (B,) sequence lengths.
            depths: (B, S) tree depth per token position.
            role_ids: (B, R) skeleton role ids (for disentanglement loss).
            role_lengths: (B,) role sequence lengths.
            kl_weight: KL annealing weight.
        """
        device = tokens.device
        cfg = self.cfg

        # 1. Encode
        mu, logvar = self.encoder(tokens, lengths)

        # 2. Reparameterize + split
        z_struct, z_content, z = self.latent(mu, logvar)

        # Track z stats
        if self.training:
            with torch.no_grad():
                m = 0.01
                self._z_struct_mean.lerp_(z_struct.mean(dim=0), m)
                self._z_struct_std.lerp_(z_struct.std(dim=0).clamp(min=1e-6), m)
                self._z_content_mean.lerp_(z_content.mean(dim=0), m)
                self._z_content_std.lerp_(z_content.std(dim=0).clamp(min=1e-6), m)

        # 3. Z → memory for cross-attention
        per_token_roles = self._extract_per_token_roles(tokens, lengths)
        z_memory = self._z_to_memory(z)

        # 4. Reconstruction loss
        if cfg.diffusion.hierarchical:
            recon_loss = self._hierarchical_loss(
                tokens, lengths, per_token_roles, depths, z_memory,
                role_ids, role_lengths,
            )
        else:
            recon_loss = self._diffusion_loss(
                tokens, lengths, per_token_roles, depths, z_memory,
            )

        # Skeleton is handled by the diffusion decoder (role tokens in
        # the interleaved sequence at depth=0). No separate skeleton loss.
        skeleton_loss = torch.tensor(0.0, device=device)

        # 5b. Length predictor loss — Poisson NLL on per-role token counts
        skel_roles, skel_mask = self._skeleton_to_padded_roles(role_ids, role_lengths)
        role_tok_counts = kwargs.get("role_token_counts")
        length_loss = torch.tensor(0.0, device=device)
        if role_tok_counts is not None:
            # Strip BOS from role_token_counts to align with skel_roles
            target_counts = role_tok_counts[:, 1:skel_roles.size(1) + 1]
            length_loss = self.length_predictor.loss(
                z, skel_roles, target_counts, skel_mask,
            )

        # 6. KL
        kl_per_dim = 0.5 * (mu.pow(2) + logvar.exp() - 1 - logvar)
        if cfg.kl_free_bits > 0:
            kl_per_dim = kl_per_dim.clamp(min=cfg.kl_free_bits)
        kl_loss = kl_weight * kl_per_dim.sum(dim=-1).mean()

        # 6b. DIP-VAE
        dip_loss = torch.tensor(0.0, device=device)
        if cfg.dip_weight > 0 and z.size(0) >= 4:
            z_c = (z - z.mean(dim=0)).float()
            cov = (z_c.T @ z_c) / max(z.size(0) - 1, 1)
            off = cov - torch.diag(cov.diag())
            dip_loss = cfg.dip_weight * off.pow(2).sum() / z.size(1) ** 2

        # 7-9. Topology + entropy share a single low-noise decode.
        # Both need a t=0.1 forward on the full batch — do it once.
        topo_rho = torch.tensor(0.0, device=device)
        topo_loss = torch.tensor(0.0, device=device)
        entropy_loss = torch.tensor(0.0, device=device)
        need_low_noise = (cfg.topo_weight > 0 and z.size(0) >= 4) or cfg.entropy_weight > 0
        if need_low_noise:
            x0_pred_low, logits_low, padding = self.low_noise_forward(
                tokens, lengths, depths, per_token_roles, z_memory,
            )

            # Topology: z-distance vs output-distance correlation
            if cfg.topo_weight > 0 and z.size(0) >= 4:
                valid = (~padding).unsqueeze(-1).float()
                decoded_repr = (x0_pred_low * valid).sum(dim=1) / valid.sum(dim=1).clamp(min=1)
                idx = torch.triu_indices(z.size(0), z.size(0), offset=1, device=device)
                z_dists = torch.cdist(z, z)[idx[0], idx[1]]
                out_dists = torch.cdist(decoded_repr, decoded_repr)[idx[0], idx[1]]
                if z_dists.numel() > 2:
                    zc = z_dists - z_dists.mean()
                    oc = out_dists - out_dists.mean()
                    denom = (zc.norm() * oc.norm()).clamp(min=1e-8)
                    topo_rho = (zc * oc).sum() / denom
                    topo_loss = cfg.topo_weight * (1.0 - topo_rho)

            # Entropy floor: penalize low-entropy positions
            if cfg.entropy_weight > 0:
                logits_ent = logits_low
                log_probs = torch.log_softmax(logits_ent, dim=-1)
                probs = log_probs.exp()
                per_pos_entropy = -(probs * log_probs).sum(dim=-1)
                valid_ent = ~padding
                shortfall = torch.clamp(cfg.entropy_floor - per_pos_entropy, min=0)
                entropy_loss = cfg.entropy_weight * (shortfall * valid_ent.float()).sum() / valid_ent.float().sum().clamp(min=1)

        # 8. Interpolation smoothness (every 4th step to save 3 decoder forwards)
        interp_loss = torch.tensor(0.0, device=device)
        global_step = kwargs.get("global_step", 0)
        if cfg.interp_weight > 0 and z.size(0) >= 4 and global_step % 4 == 0:
            n_pairs = z.size(0) // 2
            z_a = z[:n_pairs]
            z_b = z[n_pairs:2 * n_pairs]
            z_mid = 0.5 * z_a + 0.5 * z_b

            tokens_i = tokens[:n_pairs]
            lengths_i = lengths[:n_pairs]
            depths_i = depths[:n_pairs]
            roles_i = per_token_roles[:n_pairs]

            def _pool_decode(z_vec):
                mem = self._z_to_memory(z_vec)
                x0_p, _, pad_i = self.low_noise_forward(
                    tokens_i, lengths_i, depths_i, roles_i, mem,
                )
                valid_i = (~pad_i).unsqueeze(-1).float()
                return (x0_p * valid_i).sum(dim=1) / valid_i.sum(dim=1).clamp(min=1)

            repr_a = _pool_decode(z_a)
            repr_b = _pool_decode(z_b)
            repr_mid = _pool_decode(z_mid)
            expected_mid = 0.5 * (repr_a + repr_b)

            interp_loss = cfg.interp_weight * F.mse_loss(repr_mid, expected_mid)

        # 10. Disentanglement (disabled for diffusion — zeroed in config)
        disent = self.disentanglement(z_struct, z_content,
            self._make_role_bow(role_ids, role_lengths, device),
            self._make_content_bow(tokens, lengths, device),
        )

        return DiffusionVAEOutput(
            recon_loss=recon_loss,
            skeleton_loss=skeleton_loss,
            length_loss=length_loss,
            kl_loss=kl_loss,
            dip_loss=dip_loss,
            topo_rho=topo_rho,
            topo_loss=topo_loss,
            interp_loss=interp_loss,
            entropy_loss=entropy_loss,
            disentangle=disent,
            z_struct=z_struct,
            z_content=z_content,
            mu=mu,
            logvar=logvar,
        )

    def _z_to_memory(self, z: Tensor) -> Tensor:
        """Project full z to cross-attention memory tokens."""
        b = z.size(0)
        return self._z_to_mem_proj(z).reshape(b, self._num_mem_tokens, -1)

    def low_noise_forward(
        self,
        tokens: Tensor,
        lengths: Tensor,
        depths: Tensor,
        per_token_roles: Tensor,
        z_memory: Tensor,
        t_global: float = 0.1,
    ) -> tuple[Tensor, Tensor, Tensor]:
        """Single low-noise decode with proper tree noise schedule.

        Returns (x0_pred, logits, padding_mask).
        """
        b, s = tokens.shape
        device = tokens.device
        cfg = self.cfg

        t_g = torch.full((b,), t_global, device=device)
        t_per_pos = self.diffusion_decoder.tree_noise_schedule(
            t_g, depths, cfg.diffusion.depth_scale, cfg.diffusion.min_noise,
        )
        x0 = self.diffusion_decoder.token_embedding(
            tokens.clamp(max=self.diffusion_decoder.token_embedding.num_embeddings - 1)
        )
        x_t, _ = self.diffusion_decoder.add_noise(x0, t_per_pos)
        is_role = tokens >= self._role_offset
        x_t = torch.where(is_role.unsqueeze(-1), x0, x_t)
        padding = torch.arange(s, device=device).unsqueeze(0) >= lengths.unsqueeze(1)
        wp = self.diffusion_decoder.compute_word_positions(tokens, self._role_offset)
        x0_pred = self.diffusion_decoder(
            x_t, t_per_pos, per_token_roles, depths, z_memory, padding,
            word_positions=wp,
        )
        logits = self.diffusion_decoder.output_head(x0_pred)
        return x0_pred, logits, padding

    def _extract_per_token_roles(self, tokens: Tensor, lengths: Tensor) -> Tensor:
        """Forward-fill role IDs across content tokens in interleaved sequence."""
        b, s = tokens.shape
        device = tokens.device
        valid = torch.arange(s, device=device).unsqueeze(0) < lengths.unsqueeze(1)
        is_role = (tokens >= self._role_offset) & valid
        role_vals = torch.where(is_role, tokens - self._role_offset, torch.zeros_like(tokens))
        role_group = is_role.long().cumsum(dim=1)
        max_groups = max(role_group.max().item() + 1, 1)
        group_role = torch.zeros(b, max_groups, dtype=torch.long, device=device)
        group_role.scatter_(1, role_group, role_vals)
        return group_role.gather(1, role_group).clamp(max=NUM_DEP_RELATIONS - 1)

    def _diffusion_loss(
        self,
        tokens: Tensor,
        lengths: Tensor,
        per_token_roles: Tensor,
        depths: Tensor,
        z_memory: Tensor,
    ) -> Tensor:
        """Diffusion denoising loss on the full interleaved sequence.

        Both role tokens and content tokens are denoised together.
        The tree depth from the dep parse controls per-position noise:
        root tokens (depth=0) are nearly clean, leaves have full noise.
        """
        b, s = tokens.shape
        device = tokens.device

        # Clamp token ids to decoder vocab range
        full_vocab = self._decoder_vocab + len(DEP_REL_TO_ID)
        clamped = tokens.clamp(max=full_vocab - 1)

        # Get clean token embeddings
        x0 = self.diffusion_decoder.token_embedding(
            clamped.clamp(max=self.diffusion_decoder.token_embedding.num_embeddings - 1)
        )

        # Word dropout
        if self.training and self._word_dropout_p > 0:
            drop = torch.rand(b, s, 1, device=device) < self._word_dropout_p
            x0 = x0.masked_fill(drop, 0.0)

        # Random global timestep per sample
        t_global = torch.rand(b, device=device)

        # Per-position noise from tree depth
        t_per_pos = self.diffusion_decoder.tree_noise_schedule(
            t_global, depths, self.cfg.diffusion.depth_scale, self.cfg.diffusion.min_noise,
            invert=self.cfg.diffusion.invert_depth_noise,
        )

        # Corrupt content tokens only — role markers stay clean
        x_t, _ = self.diffusion_decoder.add_noise(x0, t_per_pos)
        is_role = tokens >= self._role_offset
        x_t = torch.where(is_role.unsqueeze(-1), x0, x_t)

        # Padding mask
        padding_mask = torch.arange(s, device=device).unsqueeze(0) >= lengths.unsqueeze(1)

        # Word positions from ground truth tokens
        word_positions = self.diffusion_decoder.compute_word_positions(
            tokens, self._role_offset,
        )

        # Self-conditioning: 50% of the time, run a detached forward first
        self_cond = None
        if self.training and torch.rand(1).item() < 0.5:
            with torch.no_grad():
                self_cond = self.diffusion_decoder(
                    x_t, t_per_pos, per_token_roles, depths,
                    z_memory, padding_mask, word_positions=word_positions,
                ).detach()

        # Predict clean embeddings
        x0_pred = self.diffusion_decoder(
            x_t, t_per_pos, per_token_roles, depths,
            z_memory, padding_mask, word_positions=word_positions,
            self_cond=self_cond,
        )

        # CE loss on content tokens only — role markers are given, not predicted
        logits = self.diffusion_decoder.output_head(x0_pred)
        is_content = ~padding_mask & ~is_role
        if is_content.any():
            loss = F.cross_entropy(
                logits[is_content], clamped[is_content].clamp(max=logits.size(-1) - 1),
            )
        else:
            loss = torch.tensor(0.0, device=device)

        return loss

    def _hierarchical_loss(
        self,
        tokens: Tensor,
        lengths: Tensor,
        per_token_roles: Tensor,
        depths: Tensor,
        z_memory: Tensor,
        role_ids: Tensor,
        role_lengths: Tensor,
    ) -> Tensor:
        """Hierarchical diffusion + AR loss.

        The diffusion decoder runs on the full interleaved sequence (as before)
        but the loss comes from the WordExpander AR head rather than per-token CE.
        Per-role output is pooled from the diffusion decoder, then the WordExpander
        generates tokens left-to-right within each role.
        """
        b, s = tokens.shape
        device = tokens.device
        dcfg = self.cfg.diffusion

        # Run the standard diffusion forward (with skeleton clamping)
        full_vocab = self._decoder_vocab + len(DEP_REL_TO_ID)
        clamped = tokens.clamp(max=full_vocab - 1)
        x0 = self.diffusion_decoder.token_embedding(
            clamped.clamp(max=self.diffusion_decoder.token_embedding.num_embeddings - 1)
        )

        if self.training and self._word_dropout_p > 0:
            drop = torch.rand(b, s, 1, device=device) < self._word_dropout_p
            x0 = x0.masked_fill(drop, 0.0)

        t_global = torch.rand(b, device=device)
        t_per_pos = self.diffusion_decoder.tree_noise_schedule(
            t_global, depths, dcfg.depth_scale, dcfg.min_noise,
            invert=dcfg.invert_depth_noise,
        )
        x_t, _ = self.diffusion_decoder.add_noise(x0, t_per_pos)
        is_role = tokens >= self._role_offset
        x_t = torch.where(is_role.unsqueeze(-1), x0, x_t)
        padding_mask = torch.arange(s, device=device).unsqueeze(0) >= lengths.unsqueeze(1)
        word_positions = self.diffusion_decoder.compute_word_positions(tokens, self._role_offset)

        self_cond = None
        if self.training and torch.rand(1).item() < 0.5:
            with torch.no_grad():
                self_cond = self.diffusion_decoder(
                    x_t, t_per_pos, per_token_roles, depths,
                    z_memory, padding_mask, word_positions=word_positions,
                ).detach()

        x0_pred = self.diffusion_decoder(
            x_t, t_per_pos, per_token_roles, depths,
            z_memory, padding_mask, word_positions=word_positions,
            self_cond=self_cond,
        )

        # Pool per role: mean of content token predictions within each role span
        # Identify role boundaries via cumulative role changes
        changes = torch.cat([
            torch.ones(b, 1, dtype=torch.bool, device=device),
            per_token_roles[:, 1:] != per_token_roles[:, :-1],
        ], dim=1)
        group_idx = changes.long().cumsum(dim=1) - 1  # (B, S)
        max_roles = group_idx.max().item() + 1
        max_roles = min(max_roles, self.cfg.skeleton.max_roles)

        # Pool x0_pred per role — vectorized across batch
        is_content = ~padding_mask & ~is_role
        gi_clamped = group_idx.clamp(max=max_roles - 1)
        # Zero out non-content positions so they don't contribute to scatter
        content_float = is_content.float()  # (B, S)
        # Flatten batch into combined index: batch_i * max_roles + role_j
        batch_offset = torch.arange(b, device=device).unsqueeze(1) * max_roles  # (B, 1)
        flat_idx = (batch_offset + gi_clamped) * content_float.long()  # (B, S)
        flat_idx = flat_idx.reshape(-1)  # (B*S,)

        role_vectors_flat = torch.zeros(b * max_roles, dcfg.d_model, device=device)
        role_counts_flat = torch.zeros(b * max_roles, 1, device=device)
        content_mask_flat = is_content.reshape(-1)  # (B*S,)
        preds_flat = x0_pred.reshape(-1, dcfg.d_model)  # (B*S, H)

        valid_idx = flat_idx[content_mask_flat]
        valid_preds = preds_flat[content_mask_flat]
        role_vectors_flat.scatter_add_(0, valid_idx.unsqueeze(-1).expand(-1, dcfg.d_model), valid_preds)
        role_counts_flat.scatter_add_(0, valid_idx.unsqueeze(-1), torch.ones(valid_idx.size(0), 1, device=device))

        role_vectors = (role_vectors_flat / role_counts_flat.clamp(min=1)).reshape(b, max_roles, dcfg.d_model)

        # Extract per-role target tokens — vectorized
        max_tok = dcfg.max_tokens_per_role
        # Compute position-within-role for each content token
        # Use cumsum within each (batch, role) group
        content_toks_flat = clamped.reshape(-1)  # (B*S,)
        # For each content position, compute its index within its role
        ones = torch.ones(b, s, dtype=torch.long, device=device)
        ones[~is_content] = 0
        # Cumulative count per (batch, role) group
        # Use the flat_idx to compute per-group cumcount
        role_pos = torch.zeros(b * max_roles, dtype=torch.long, device=device)
        target_tokens = torch.zeros(b, max_roles, max_tok, dtype=torch.long, device=device)
        target_lengths = torch.zeros(b, max_roles, dtype=torch.long, device=device)

        # This part is hard to fully vectorize — use a compact loop over content tokens only
        valid_batch_idx = torch.arange(b, device=device).unsqueeze(1).expand_as(is_content)[is_content]
        valid_role_idx = gi_clamped[is_content]
        valid_content_toks = clamped[is_content]
        # Compute position within each (batch, role) group via cumcount
        combined_key = valid_batch_idx * max_roles + valid_role_idx
        # Sequential cumcount — unavoidable for correctness, but over content tokens only (not B*S)
        pos_counter = torch.zeros(b * max_roles, dtype=torch.long, device=device)
        positions = torch.empty_like(combined_key)
        for i in range(combined_key.size(0)):
            k = combined_key[i].item()
            positions[i] = pos_counter[k]
            pos_counter[k] += 1

        # Fill target_tokens using the computed positions
        valid_pos = positions.clamp(max=max_tok - 1)
        in_range = positions < max_tok
        target_tokens[valid_batch_idx[in_range], valid_role_idx[in_range], valid_pos[in_range]] = valid_content_toks[in_range]
        target_lengths = pos_counter.clamp(max=max_tok).reshape(b, max_roles)

        # AR loss from WordExpander
        ar_loss = self.word_expander(role_vectors, target_tokens, target_lengths)

        return ar_loss

    def _extract_content(
        self, tokens: Tensor, lengths: Tensor, dep_depths: Tensor,
    ) -> tuple[Tensor, Tensor, Tensor, Tensor]:
        """Extract content tokens, their roles, and depths from interleaved sequence."""
        b, s = tokens.shape
        device = tokens.device
        role_offset = self.cfg.spm_vocab_size + 2

        valid = torch.arange(s, device=device).unsqueeze(0) < lengths.unsqueeze(1)
        is_role = (tokens >= role_offset) & valid
        is_content = (~is_role) & (tokens > 0) & valid

        # Forward-fill role IDs
        role_vals = torch.where(is_role, tokens - role_offset, torch.zeros_like(tokens))
        role_group = is_role.long().cumsum(dim=1)
        max_groups = role_group.max().item() + 1
        group_role = torch.zeros(b, max_groups, dtype=torch.long, device=device)
        group_role.scatter_(1, role_group, role_vals)
        per_pos_role = group_role.gather(1, role_group).clamp(max=NUM_DEP_RELATIONS - 1)

        # Compact content tokens
        content_counts = is_content.sum(dim=1)
        max_content = content_counts.max().item()

        content_tokens = torch.zeros(b, max_content, dtype=torch.long, device=device)
        content_roles = torch.zeros(b, max_content, dtype=torch.long, device=device)
        content_depths = torch.zeros(b, max_content, dtype=torch.long, device=device)

        for i in range(b):
            idx = is_content[i].nonzero(as_tuple=True)[0]
            n = idx.numel()
            content_tokens[i, :n] = tokens[i, idx]
            content_roles[i, :n] = per_pos_role[i, idx]
            if dep_depths.size(1) >= n:
                content_depths[i, :n] = dep_depths[i, :n]

        return content_tokens, content_counts, content_roles, content_depths

    def _skeleton_to_padded_roles(
        self, role_ids: Tensor, role_lengths: Tensor,
    ) -> tuple[Tensor, Tensor]:
        """Convert teacher-forced skeleton to padded roles + mask for projector."""
        from lfm.generator.dep_tree_vae.skeleton import SKEL_BOS, SKEL_EOS

        b = role_ids.size(0)
        device = role_ids.device
        roles_no_bos = role_ids[:, 1:]
        max_r = roles_no_bos.size(1)
        actual_len = (role_lengths - 1).clamp(min=1)

        mask = torch.arange(max_r, device=device).unsqueeze(0) < actual_len.unsqueeze(1)
        clamped = roles_no_bos.clamp(max=NUM_DEP_RELATIONS - 1)
        # Zero out past-length positions
        clamped = clamped * mask.long()

        return clamped, mask

    def _make_role_bow(self, role_ids: Tensor, role_lengths: Tensor, device: torch.device) -> Tensor:
        b = role_ids.size(0)
        bow = torch.zeros(b, NUM_DEP_RELATIONS, device=device)
        mask = torch.arange(role_ids.size(1), device=device).unsqueeze(0) < role_lengths.unsqueeze(1)
        for i in range(b):
            valid = role_ids[i][mask[i]]
            valid = valid[valid < NUM_DEP_RELATIONS]
            if valid.numel() > 0:
                bow[i].scatter_(0, valid, 1.0)
        return bow

    def _make_content_bow(self, tokens: Tensor, lengths: Tensor, device: torch.device) -> Tensor:
        b = tokens.size(0)
        role_offset = self.cfg.spm_vocab_size + 2
        bow = torch.zeros(b, self.vocab_size + 3, device=device)
        mask = torch.arange(tokens.size(1), device=device).unsqueeze(0) < lengths.unsqueeze(1)
        for i in range(b):
            valid = tokens[i][mask[i]]
            content = valid[valid < role_offset]
            if content.numel() > 0:
                bow[i].scatter_add_(0, content, torch.ones_like(content, dtype=torch.float))
        return bow

    def trainable_parameters(self) -> list[dict]:
        """Parameter groups for optimizer."""
        groups = [
            {"params": list(self.encoder.parameters())},
            {"params": list(self.latent.parameters())},
            {"params": list(self.phrase_projector.parameters())},
            {"params": list(self.diffusion_decoder.parameters())},
            {"params": list(self.length_predictor.parameters())},
            {"params": list(self.disentanglement.parameters())},
        ]
        if hasattr(self, "word_expander"):
            groups.append({"params": list(self.word_expander.parameters())})
        return groups
