"""Paragraph-coherence diagnostics for the ContrastiveGame.

HYPOTHESIS
----------
The multi-phrase expressions generated by the ContrastiveGame should
behave like coherent paragraphs: K phrases conditioned on the same
anchor should be more semantically related to each other than to
phrases from a different anchor's expression.

If this already holds, the DiffusionZGenerator's self-attention is
coordinating z-codes into a topically unified neighbourhood without
any explicit loss term — no architectural change needed.

If it does NOT hold (intra_sim ≈ inter_sim), then adding an intra-
expression InfoNCE on phrase-level projections is justified: it would
teach the z-generator to produce topically coherent z-codes, and as a
side effect constrain them to the decoder's training distribution
(mitigating cycling pathologies).

PROPOSED LOSS (pending empirical justification)
-----------------------------------------------
For each expression with K phrase projections p_1..p_K:

    L_intra = InfoNCE where positives are co-phrases within the same
              expression and negatives are phrases from other expressions.

This is directly analogous to the existing hidden_infonce but applied
at the per-phrase level rather than the pooled-expression level. The
signal would propagate through hidden_proj and into the z-generator's
self-attention, teaching it to produce mutually consistent z-codes.

DIAGNOSTICS
-----------
1. Phrase-projection similarity (hidden_proj space)
   - intra_sim : mean cosine similarity between phrases within same
                 expression
   - inter_sim : same, across different expressions
   - ratio     : intra / inter  (>1.3 = coherent; ~1.0 = random)

2. Z-code similarity (normalised by VAE prior stats)
   - z_intra_sim / z_inter_sim / z_ratio
   Tells us whether the z-gen self-attention is already coordinating
   z-codes or each is produced independently.

3. Surface quality per sample
   - token_dominance  : max single-token fraction        (cycling if >0.25)
   - repeat_bigram    : fraction of adjacent-equal pairs (cycling if >0.15)
   - unique_ratio     : unique tokens / total             (cycling if <0.45)
   - acceptance_rate  : fraction passing all three filters

4. Per-slot degeneration rate
   For each phrase slot k in 0..K-1, fraction of that slot's phrases
   that are degenerate. Systematic slot failure indicates a structural
   z-gen coordination failure specific to that position.

INTERPRETATION GUIDE
--------------------
- proj_ratio > 1.3  AND  acceptance_rate > 0.70:
    Expressions are coherent and clean. Proceed to corpus generation.

- proj_ratio < 1.1  AND  acceptance_rate > 0.60:
    Phrases are semantically unrelated despite clean surface.
    Intra-expression InfoNCE is justified.

- acceptance_rate < 0.60:
    Surface cycling still dominant. Continue z_prior + EOS-bias
    training before considering coherence losses.

- A specific slot k with degeneration rate > 0.50:
    Systematic OOD z-codes for that slot position.
    Consider slot-position-aware z_prior or slot embeddings.

USAGE
-----
    poetry run python scripts/diagnostics/contrastive_coherence_diag.py \\
        --checkpoint data/contrastive_dep_tree_v1/best.pt              \\
        --config     configs/contrastive_dep_tree_v1_vast.yaml          \\
        --n-samples  512
"""

from __future__ import annotations

import argparse
import logging
from collections import Counter

import numpy as np
import torch
import torch.nn.functional as F
import yaml
from torch import Tensor

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
logger = logging.getLogger(__name__)


# ─── model loading ──────────────────────────────────────────────────────────

def _load_game(checkpoint: str, config: str, device: torch.device):
    from lfm.agents.config import CurriculumConfig
    from lfm.agents.games.contrastive import ContrastiveGame, ContrastiveGameConfig
    from lfm.generator.dep_tree_vae.config import DepTreeVAEConfig
    from lfm.generator.dep_tree_vae.model import DepTreeVAE

    with open(config) as f:
        cfg_dict = yaml.safe_load(f) or {}

    curriculum_kwargs = {}
    for key in ("enabled", "warmup_steps", "start_hard_ratio", "end_hard_ratio"):
        if key in cfg_dict:
            curriculum_kwargs[key] = cfg_dict.pop(key)
    if curriculum_kwargs:
        cfg_dict["curriculum"] = CurriculumConfig(**curriculum_kwargs)

    game_cfg = ContrastiveGameConfig(**cfg_dict)
    vae = _load_vae(game_cfg, device)
    game = ContrastiveGame(game_cfg, vae).to(device)

    ckpt = torch.load(checkpoint, map_location=device, weights_only=False)
    game.load_checkpoint_state(ckpt)
    game.eval()
    logger.info("Loaded step=%s  acc=%.1f%%", ckpt.get("step", "?"), ckpt.get("accuracy", 0) * 100)
    return game, game_cfg


def _load_vae(cfg, device: torch.device):
    from lfm.generator.dep_tree_vae.config import DepTreeVAEConfig
    from lfm.generator.dep_tree_vae.model import DepTreeVAE

    vae_dict = yaml.safe_load(open(cfg.vae_config))
    vae_dict.pop("model_type", None)
    vae_dict["spm_model_path"] = cfg.spm_path
    vae_dict["output_dir"] = cfg.output_dir
    vae_dict["corpus_unigram_path"] = ""

    ckpt = torch.load(cfg.vae_checkpoint, map_location=device, weights_only=False)
    state = ckpt["model_state"]
    if not any(k.startswith("length_head") for k in state):
        vae_dict["length_pred_weight"] = 0.0
        vae_dict["use_predicted_length_at_decode"] = False
    if not any(k.startswith("tokens_per_role_head") for k in state):
        vae_dict["tokens_per_role_weight"] = 0.0
    vae_dict["use_decoder_role_emb"] = any(k.startswith("decoder_role_emb") for k in state)

    vae_cfg = DepTreeVAEConfig(**vae_dict)
    vae = DepTreeVAE(vae_cfg, vocab_size=vae_cfg.spm_vocab_size + 50).to(device)
    vae.load_state_dict(state, strict=False)
    return vae


def _sample_anchors(cfg, n: int, device: torch.device) -> Tensor:
    from lfm.embeddings.store import EmbeddingStore
    store = EmbeddingStore(cfg.embedding_store_dir)
    store.load()
    idx = np.random.randint(0, store.num_passages, size=n)
    return torch.tensor(store.get_embeddings(idx), dtype=torch.float32, device=device)


# ─── per-phrase extraction ──────────────────────────────────────────────────

def _phrase_projections(game, expr) -> Tensor:
    """(B, K, E) — hidden_proj applied to each phrase's mean-pooled hidden."""
    K = expr.z_seq.size(1)
    B, KT, H = expr.hidden.shape
    T = KT // K
    h = expr.hidden.reshape(B, K, T, H)
    m = expr.mask.reshape(B, K, T).float()
    lengths = m.sum(-1, keepdim=True).clamp(min=1)
    pooled = (h * m.unsqueeze(-1)).sum(-2) / lengths    # (B, K, H)
    return game.hidden_proj(pooled)                     # (B, K, E)


def _z_normed(game, expr) -> Tensor:
    """(B, K, D) — z-codes normalised by VAE prior stats (or raw if unavailable)."""
    z = expr.z_seq
    if game.z_prior is not None:
        return (z - game.z_prior.prior_mean) / game.z_prior.prior_std
    return z


# ─── similarity metrics ─────────────────────────────────────────────────────

def _pairwise_cosine_stats(vecs: Tensor) -> tuple[float, float]:
    """Mean intra-expression and inter-expression cosine similarity.

    Args:
        vecs: (N, K, E)
    Returns:
        (intra_mean, inter_mean)
    """
    N, K, E = vecs.shape
    n = F.normalize(vecs, dim=-1)   # (N, K, E)

    intra_vals: list[float] = []
    for i in range(N):
        ni = n[i]                                          # (K, E)
        sim = ni @ ni.t()                                  # (K, K)
        off_diag = ~torch.eye(K, dtype=torch.bool, device=sim.device)
        intra_vals.append(sim[off_diag].mean().item())
    intra = float(np.mean(intra_vals))

    flat = n.reshape(N * K, E)
    rng = torch.randperm(N * K, device=flat.device)
    idx_a, idx_b = rng[:N], rng[N:2 * N] if len(rng) >= 2 * N else rng[N:]
    if len(idx_b) < 4:
        return intra, float("nan")
    same_expr = (idx_a // K) == (idx_b // K)
    a = flat[idx_a[~same_expr]]
    b = flat[idx_b[~same_expr]]
    inter = (a * b).sum(-1).mean().item() if len(a) > 0 else float("nan")
    return intra, inter


# ─── surface quality ────────────────────────────────────────────────────────

def _token_metrics(tokens: list[int]) -> dict[str, float]:
    if len(tokens) < 2:
        return {"token_dominance": 1.0, "repeat_bigram": 1.0, "unique_ratio": 0.0}
    n = len(tokens)
    counts = Counter(tokens)
    return {
        "token_dominance": counts.most_common(1)[0][1] / n,
        "repeat_bigram":   sum(1 for a, b in zip(tokens, tokens[1:]) if a == b) / (n - 1),
        "unique_ratio":    len(counts) / n,
    }


def _is_cycling(m: dict[str, float]) -> bool:
    return m["token_dominance"] > 0.25 or m["repeat_bigram"] > 0.15 or m["unique_ratio"] < 0.45


def _surface_analysis(tokens_cpu: Tensor, mask_cpu: Tensor, eos_id: int, K: int) -> dict:
    B, KT = tokens_cpu.shape
    T = KT // K
    n_degenerate = 0
    slot_degenerate = [0] * K
    metrics_all: list[dict] = []

    for b in range(B):
        row, mrow = tokens_cpu[b], mask_cpu[b]
        full = [int(t) for t, m in zip(row, mrow) if m and int(t) != eos_id]
        m = _token_metrics(full)
        metrics_all.append(m)
        if _is_cycling(m):
            n_degenerate += 1
        for k in range(K):
            slot_toks = [
                int(row[k * T + i]) for i in range(T)
                if mask_cpu[b, k * T + i] and int(row[k * T + i]) != eos_id
            ]
            if _is_cycling(_token_metrics(slot_toks)):
                slot_degenerate[k] += 1

    return {
        "acceptance_rate":       1.0 - n_degenerate / B,
        "mean_token_dominance":  float(np.mean([m["token_dominance"] for m in metrics_all])),
        "mean_repeat_bigram":    float(np.mean([m["repeat_bigram"]    for m in metrics_all])),
        "mean_unique_ratio":     float(np.mean([m["unique_ratio"]     for m in metrics_all])),
        "slot_degenerate_rate":  [s / B for s in slot_degenerate],
    }


# ─── generation loop ────────────────────────────────────────────────────────

def run_diagnostics(game, cfg, n_samples: int, batch_size: int, device: torch.device) -> dict:
    proj_list, z_list, tok_list, mask_list = [], [], [], []
    K = None
    n_done = 0

    with torch.no_grad():
        while n_done < n_samples:
            n_batch = min(batch_size, n_samples - n_done)
            anchor = _sample_anchors(cfg, n_batch, device)
            expr = game._generate(anchor)
            if K is None:
                K = expr.z_seq.size(1)
            proj_list.append(_phrase_projections(game, expr).cpu())
            z_list.append(_z_normed(game, expr).cpu())
            tok_list.append(expr.tokens_cpu)
            mask_list.append(expr.gen_mask_cpu)
            n_done += n_batch
            logger.info("Generated %d / %d", n_done, n_samples)

    proj  = torch.cat(proj_list,  dim=0)
    z     = torch.cat(z_list,     dim=0)
    toks  = torch.cat(tok_list,   dim=0)
    masks = torch.cat(mask_list,  dim=0)

    proj_intra, proj_inter = _pairwise_cosine_stats(proj)
    z_intra,    z_inter    = _pairwise_cosine_stats(z)
    surface = _surface_analysis(toks, masks, game._eos_id, K)

    return {
        "n_samples":      n_done,
        "K":              K,
        "proj_intra_sim": proj_intra,
        "proj_inter_sim": proj_inter,
        "proj_ratio":     proj_intra / proj_inter if proj_inter else float("nan"),
        "z_intra_sim":    z_intra,
        "z_inter_sim":    z_inter,
        "z_ratio":        z_intra / z_inter if z_inter else float("nan"),
        **surface,
    }


# ─── report ─────────────────────────────────────────────────────────────────

def _print_report(r: dict) -> None:
    sep = "─" * 62
    print(f"\n{sep}")
    print("  ContrastiveGame — Paragraph Coherence Diagnostics")
    print(sep)
    print(f"  n_samples = {r['n_samples']}   K = {r['K']} phrases/expression")
    print()

    def _flag(val, threshold, label_ok, label_bad, higher_is_better=True):
        ok = val > threshold if higher_is_better else val < threshold
        return f"  {'✓' if ok else '✗'}  {label_ok if ok else label_bad}"

    print("  PHRASE PROJECTION SIMILARITY  (hidden_proj space)")
    print(f"    intra-expression : {r['proj_intra_sim']:+.4f}")
    print(f"    inter-expression : {r['proj_inter_sim']:+.4f}")
    ratio = r["proj_ratio"]
    flag = "✓ coherent" if ratio > 1.3 else ("~ marginal" if ratio > 1.1 else "✗ incoherent — intra-NCE may help")
    print(f"    ratio            :  {ratio:.3f}  {flag}")
    print()

    print("  Z-CODE SIMILARITY  (normalised by VAE prior)")
    print(f"    intra-expression : {r['z_intra_sim']:+.4f}")
    print(f"    inter-expression : {r['z_inter_sim']:+.4f}")
    zr = r["z_ratio"]
    zflag = "✓ z-gen coordinating" if zr > 1.2 else "✗ z-codes not coordinated"
    print(f"    ratio            :  {zr:.3f}  {zflag}")
    print()

    print("  SURFACE QUALITY")
    acc = r["acceptance_rate"]
    print(f"    acceptance rate      : {acc*100:5.1f}%  {'✓' if acc > 0.70 else ('~' if acc > 0.55 else '✗')}")
    print(f"    mean token dominance : {r['mean_token_dominance']:.3f}  (cycling threshold: 0.25)")
    print(f"    mean repeat bigram   : {r['mean_repeat_bigram']:.3f}  (cycling threshold: 0.15)")
    print(f"    mean unique ratio    : {r['mean_unique_ratio']:.3f}  (cycling threshold: 0.45)")
    print()

    print("  PER-SLOT DEGENERATION RATE")
    for k, rate in enumerate(r["slot_degenerate_rate"]):
        bar = "█" * int(rate * 24)
        note = "  ← systematic failure" if rate > 0.50 else ""
        print(f"    slot {k} : {rate*100:5.1f}%  {bar}{note}")
    print()

    print("  DECISION GUIDE")
    if ratio > 1.3 and acc > 0.70:
        print("  → Expressions are coherent and surface-clean.")
        print("    Proceed to corpus generation.")
    elif ratio < 1.1 and acc > 0.60:
        print("  → Phrases are semantically unrelated despite clean surface.")
        print("    Intra-expression InfoNCE on phrase projections is justified.")
    elif acc < 0.60:
        print("  → Surface cycling still dominant.")
        print("    Prioritise z_prior training before changing architecture.")
    else:
        print("  → Mixed quality. Improve surface acceptance first,")
        print("    then reassess coherence ratio.")
    print(sep + "\n")


# ─── CLI ────────────────────────────────────────────────────────────────────

def _args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--checkpoint", required=True, help="Game checkpoint (.pt)")
    p.add_argument("--config",     required=True, help="ContrastiveGameConfig YAML")
    p.add_argument("--n-samples",  type=int, default=512)
    p.add_argument("--batch-size", type=int, default=64)
    p.add_argument("--device",     default="cuda")
    p.add_argument("--seed",       type=int, default=42)
    return p.parse_args()


def main() -> None:
    args = _args()
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    device = torch.device(args.device)
    game, cfg = _load_game(args.checkpoint, args.config, device)
    results = run_diagnostics(game, cfg, args.n_samples, args.batch_size, device)
    _print_report(results)


if __name__ == "__main__":
    main()
