import Link from "next/link";
import { listCorpora } from "@/lib/corpora";
import { formatNumber } from "@/lib/format";

export const metadata = {
  title: "Corpora — LFM",
};

/**
 * Top-level listing of available corpora.  Server component; data
 * comes from the local data-access module (which today returns
 * mock data but will read from disk once wired up).
 */
export default async function CorporaListPage() {
  const corpora = await listCorpora();

  return (
    <div className="flex-1 min-h-0 overflow-y-auto flex flex-col p-10 gap-6 max-w-[120rem] w-full">
      <header className="flex flex-col gap-1">
        <h1 className="text-2xl font-semibold tracking-tight">Corpora</h1>
        <p className="text-sm text-muted">
          Datasets generated by the LFM pipeline.  Select one to inspect
          its samples and metadata.
        </p>
      </header>

      <ul className="grid grid-cols-[repeat(auto-fill,minmax(22rem,1fr))] gap-4">
        {corpora.map((c) => (
          <li key={c.id}>
            <Link
              href={`/corpora/${encodeURIComponent(c.id)}`}
              className="block h-full rounded-[var(--radius)] border border-separator hover:border-foreground/40 bg-surface/60 hover:bg-surface transition-colors p-5 focus-visible:outline-none focus-visible:border-foreground/60"
            >
              <div className="flex flex-col gap-2">
                <div className="flex items-baseline justify-between gap-3">
                  <h2 className="font-semibold text-base text-accent">{c.name}</h2>
                  <span className="text-xs text-muted">
                    {formatNumber(c.sampleCount)} samples
                  </span>
                </div>
                <p className="text-sm text-muted line-clamp-2">
                  {c.description}
                </p>
                <div className="flex gap-2 flex-wrap pt-2">
                  {c.tags.map((t) => (
                    <span
                      key={t}
                      className="px-2 py-0.5 text-xs rounded-[calc(var(--radius)*0.6)] bg-default/70 text-foreground/80"
                    >
                      {t}
                    </span>
                  ))}
                </div>
              </div>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}
